@startuml packages_crew-chief
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "benchmark\n1 python file" as benchmark
rectangle "crew_chief\n1 child pkg, 10 modules\n18 python files\nexamples: __main__, agent, cli" as crew_chief
rectangle "crew_chief.__main__\n1 python file" as crew_chief.__main__
rectangle "crew_chief.agent\n1 python file" as crew_chief.agent
rectangle "crew_chief.cli\n1 python file" as crew_chief.cli
rectangle "crew_chief.client\n1 python file" as crew_chief.client
rectangle "crew_chief.config_loader\n1 python file" as crew_chief.config_loader
rectangle "crew_chief.dispatcher\n1 python file" as crew_chief.dispatcher
rectangle "crew_chief.listener\n1 python file" as crew_chief.listener
rectangle "crew_chief.model_output_utils\n1 python file" as crew_chief.model_output_utils
rectangle "crew_chief.prompt_utils\n1 python file" as crew_chief.prompt_utils
rectangle "crew_chief.providers\n0 child pkg, 6 modules\n7 python files\nexamples: anthropic, base, cli" as crew_chief.providers
rectangle "crew_chief.providers.anthropic\n1 python file" as crew_chief.providers.anthropic
rectangle "crew_chief.providers.base\n1 python file" as crew_chief.providers.base
rectangle "crew_chief.providers.cli\n1 python file" as crew_chief.providers.cli
rectangle "crew_chief.providers.ollama\n1 python file" as crew_chief.providers.ollama
rectangle "crew_chief.providers.openai\n1 python file" as crew_chief.providers.openai
rectangle "crew_chief.providers.prompt_utils\n1 python file" as crew_chief.providers.prompt_utils
rectangle "crew_chief.tools\n1 python file" as crew_chief.tools
rectangle "report\n1 python file" as report
crew_chief --> crew_chief.agent
crew_chief --> crew_chief.client
crew_chief --> crew_chief.providers
crew_chief --> crew_chief.tools
crew_chief.__main__ --> crew_chief.cli
crew_chief.agent --> crew_chief.model_output_utils
crew_chief.agent --> crew_chief.providers.base
crew_chief.cli --> crew_chief.agent
crew_chief.cli --> crew_chief.client
crew_chief.cli --> crew_chief.config_loader
crew_chief.cli --> crew_chief.dispatcher
crew_chief.cli --> crew_chief.listener
crew_chief.cli --> crew_chief.providers
crew_chief.cli --> crew_chief.providers.anthropic
crew_chief.cli --> crew_chief.providers.cli
crew_chief.cli --> crew_chief.providers.ollama
crew_chief.cli --> crew_chief.providers.openai
crew_chief.cli --> crew_chief.tools
crew_chief.client --> crew_chief.prompt_utils
crew_chief.listener --> crew_chief.agent
crew_chief.listener --> crew_chief.client
crew_chief.listener --> crew_chief.config_loader
crew_chief.listener --> crew_chief.dispatcher
crew_chief.listener --> crew_chief.providers
crew_chief.listener --> crew_chief.tools
crew_chief.providers --> crew_chief.providers.anthropic
crew_chief.providers --> crew_chief.providers.base
crew_chief.providers --> crew_chief.providers.cli
crew_chief.providers --> crew_chief.providers.ollama
crew_chief.providers --> crew_chief.providers.openai
crew_chief.providers.anthropic --> crew_chief.providers.base
crew_chief.providers.anthropic --> crew_chief.providers.prompt_utils
crew_chief.providers.cli --> crew_chief.providers.base
crew_chief.providers.cli --> crew_chief.providers.prompt_utils
crew_chief.providers.ollama --> crew_chief.providers.base
crew_chief.providers.ollama --> crew_chief.providers.prompt_utils
crew_chief.providers.openai --> crew_chief.providers.base
crew_chief.providers.openai --> crew_chief.providers.prompt_utils
crew_chief.providers.prompt_utils --> crew_chief.prompt_utils
crew_chief.tools --> crew_chief.dispatcher
crew_chief.tools --> crew_chief.providers.base
@enduml
